language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: KVFg6vWOv7HqB5awfr2NVxnuavIHk2CgMX/B+F4yelLiqNtoPvGgBZDwQuJK6IVEmaaoYid93QlhWE6vXoekEqNT7Q++u3LkQ9XR+lzbic4I+QYwrwzF14lTH6zi7nWhF+8vtZCDOssqBYTSbM7D34v/7qL1j6NOVyS6ltu7mEkVOs0BL9vNw4PZnF6q96n89n/j/41pYlTzawv4w98OawkRj2RoOhsF1D+3B+ZkwDBcV6ikPeooI5MsUdIaL/XJcyCv8suHzlmVp9I+ZQ3iyYZ8MEtkh3B8seSeL9xeOxurBeDh4gv4gkqKthST1LIJfTdWUrKKxe1zJhEk/GtaXT86/8Fc7dCu2BmkdVnXtb0krhIagYUOIyBbcQvdN+UTFxu2NzB3Y7cRED9J7VPAFOfIqTeuiFPxdaTrFr26nKPbiz46TuhXta2MVSMymNW/3ao2yKhuoA34LacJAHBnPRPZnetxf5V7fsFCl3aOTnWLWBmmp5zE34FQvQSgZMxxlZDZuq1kjw4l8iN9H/Y679nzK1J619g/oJMUmZavkW2sJvHkfQ7vz8ig6/NusanhYjFs6bsP0mCHEKgwZBGFr/QP1vVjFDOblnruUqbYarp6RytvjGKVgwl4zVsOFKdPbDHD5sDfeUodlJ4wgXuW/x7W5cBFFIDDyk2hp4Ous64=
  app: protected-temple-26211
  on:
    repo: BlitzDampfwalze/node-shopping-list-integration-tests
